name: guideng
services:
  server:
    source:
      type: image
      image: facilisvelox/guideng-server:latest
    ports:
      - id: http
        port: 8080
        type: HTTP
    env:
      GUIDENG_BIND: 0.0.0.0:8080
      GUIDENG_DATABASE_URL: /data/guideng.sqlite3
      GUIDENG_LOG_PATH: /data/guideng.log
      GUIDENG_CORS_ORIGINS: "*"
      GUIDENG_TOKEN:
        default: ""
    volumes:
      - id: data
        dir: /data
  client:
    source:
      type: image
      image: facilisvelox/guideng-client:latest
    ports:
      - id: http
        port: 80
        type: HTTP
